<?php
namespace app\wechat\controller;

use app\common\controller\Common;
use think\Controller;
use think\Log;
use think\Request;

class Wxbase extends Common
{
   public function _initialize()
   {
/*         if (request()->isMobile()) {
               if (empty(session('user'))) {
                   $msg = findById("user", array("name|mobile" =>'18888888888'), "id,password,iqbtId,etprsId,type,avatar,status,name,realname,mobile,validTime");
                   if (!empty($msg['data'])) {
                       //用户头像。
                       $avatarId = $msg["data"]["avatar"];
                       $msg["data"]["avatarpath"] = "";
                       $msg2 = findById("sysFile", array("id" => $avatarId), "savePath");
                       if (!empty($msg2['data'])) {
                           $path = ROOT_PATH . 'public' . "/" . $msg2["data"]["savePath"];
                           if (file_exists($path)) {
                               $msg["data"]["avatarpath"] = $msg2["data"]["savePath"];
                           }
                       }
                       //不把密码存储到session里
                       unset($msg["data"]["password"]);
                       //如果是企业用户
                       if (!empty($msg['data']['etprsId'])) {
                           $msg['data']['etprsName'] = getField('etprs', ['id' => $msg['data']['etprsId']], 'name');
                       }
                       //将 用户信息记录到session
                       session('user', $msg["data"]);
                       session('userId', $msg["data"]["id"]);
                       session('iqbtId', $msg["data"]["iqbtId"]);
                       if (session('user.status') != 6018004) {
                           $iqbtname = getField("incubator", array("id" => $msg["data"]["iqbtId"]), "name");
                           session('iqbtName', $iqbtname);
                       }
                   }
               }
           }*/
       parent::_initialize(); // TODO: Change the autogenerated stub
       // 检查openId是否有效
       if(!session("openId")){
           Log::notice('wxbase:openId is null');
           $this->redirect(url('wechat/Auth/oauth2_access'));
       }
       $openId=session("openId");
//       dump($openId);exit;
       if(empty($openId)){
           //todo 跳转到空页面、没有获取到openId
           dump('没有获取到openId');
           Log::notice(json_encode("跳转到空页面、没有获取到openId"));
       }
       $msg = findById('user',['openId'=>$openId],'id,iqbtId,mobile,status,etprsId,type');
//       Log::notice(json_encode('***'.$msg['code']));
       // 假设用户已经绑定

       // 角色在这里判断绑定什么的比较好
       if(empty($msg['code'])){
           //todo 跳转到绑定页面
           $this->redirect(url('wechat/Auth/bind'));
       }else{

           //判断是否为未通过审核账号
           if($msg['data']['status']==6018005){
                echo ('您的账号正在审核中,请耐心等待');exit;
           }
           //判断孵化器是否过期
           $res=findById('incubator',['id'=>$msg['data']['iqbtId']],'validTime');
           if($res['data']['validTime']!=0 && $res['data']['validTime']<time()){
               echo ('您的空间合同已过期,请联系创8官方客服续费');exit;
           }
           Log::notice(json_encode($msg));
           //将用户数据保存到session里
           session('userId',$msg['data']['id']);
           session('iqbtId',$msg['data']['iqbtId']);
           session('user',$msg['data']);
           if(session('user.status')!=6018004) {
               $iqbtname = getField("incubator", array("id" => $msg["data"]["iqbtId"]), "name");
               session('iqbtName',$iqbtname);
           }
           if(session('user.type')==6019002){//企业用户获取企业名称
               $etprsname = getField("etprs", array("id" => $msg["data"]["etprsId"]), "name");
               session('etprsName',$etprsname);
           }
       }
   }

    /***
     *
     */
    function initopenId()
    {
        try {
            /*$rec_url = urlencode($this->authnotify);
            $appid = 'wx0e2195a85fb69f6f';
            $appsecret = '6f34b486e9215dc6dd7e5486519e4aa1';
            $authnotify = null;
            $url = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=".$appid."&redirect_uri=".$rec_url."&oauth_response.php&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect";
            //$this->redirect($url);
            $ret = file_get_contents($url);
            $userdata = json_decode($ret, true);
            Log::notice(json_encode($userdata));
            die();*/
            $auth=new Auth();
            $auth->oauth2_access();
//            $auth->oauth2_access_token()
            die();
        } catch (\Exception $e) {
            //记录事务
            c_Log($e);
            //Db::rollback();
            return json(array('code' => '0', 'msg' => $e->getMessage(), 'data' => []));
        }
    }


}
